//@ui5-bundle testTree/testTree/Component-preload.js
jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"testTree/testTree/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","testTree/testTree/model/models"],function(e,t,i){"use strict";return e.extend("testTree.testTree.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(i.createDeviceModel(),"device")}})});
},
	"testTree/testTree/appconfig.json":'{"name":"Hierarchie Ext. SAPUI5","provider":"AWA_LI_Consulting","description":"Extension SAPUI5","version":"1.0.0","icon":"https://raw.githubusercontent.com/SAP-samples/fsm-extension-sample/refactor/samples/service-contract/icon.png"}',
	"testTree/testTree/controller/View1.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";return e.extend("testTree.testTree.controller.View1",{onInit:function(){}})});
},
	"testTree/testTree/i18n/i18n.properties":'title=Title\nappTitle=testTree\nappDescription=App Description',
	"testTree/testTree/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"testTree.testTree","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","sourceTemplate":{"id":"ui5template.basicSAPUI5ApplicationProject","version":"1.40.12"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"rootView":{"viewName":"testTree.testTree.view.View1","type":"XML","async":true,"id":"View1"},"dependencies":{"minUI5Version":"1.65.6","libs":{"sap.ui.layout":{},"sap.ui.core":{},"sap.m":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"testTree.testTree.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"testTree.testTree.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteView1","pattern":"RouteView1","target":["TargetView1"]}],"targets":{"TargetView1":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"View1","viewName":"View1"}}}}}',
	"testTree/testTree/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"testTree/testTree/view/View1.view.xml":'\n<mvc:View controllerName="testTree.testTree.controller.View1" xmlns:mvc="sap.ui.core.mvc" displayBlock="true"  xmlns="sap.m"><Shell id="shell"><App id="app"><pages><Page id="page" title="Attributes pulled from FSM shell app"><content><sap.ui.layout:Grid xmlns:sap.ui.layout="sap.ui.layout" id="grid0"><sap.ui.layout:content><ObjectListItem title="account" intro="Account" icon="sap-icon://account" id="account"/><ObjectListItem title="accountID" intro="Account ID" icon="sap-icon://account" id="accountID"/><ObjectListItem title="company" intro="Company" icon="sap-icon://factory" id="company"/><ObjectListItem title="companyID" intro="Company ID" icon="sap-icon://factory" id="companyID"/><ObjectListItem title="user" intro="User" icon="sap-icon://account" id="user"/><ObjectListItem title="userID" intro="User ID" icon="sap-icon://account" id="userID"/><ObjectListItem title="locale" intro="Selected Locale" icon="sap-icon://globe" id="selLocale"/></sap.ui.layout:content></sap.ui.layout:Grid></content></Page></pages></App></Shell></mvc:View>'
}});
